config/routes.rb
LeadTracker::Application.routes.draw do

  get "lead_notes/get_notes"
  resources :lead_notes

  get "schedule/add_appointment"

  get "schedule/get_appointments"

  resources :partner_types

  resource :session

  match '/login' => "sessions#new", :as => "login"

  match '/logout' => "sessions#destroy", :as => "logout"

  resources :packages

  resources :installers

  resources :users

  match 'leads/new_lead' => "leads#new_lead"
  match 'leads/my_lead_status' => "leads#my_lead_status"
  match 'leads/partner_lead_status' => "leads#partner_lead_status"
  match 'leads/lead_admin' => "leads#lead_admin"
  resources :leads

  match 'agents/start' => "agents#start"# , :as => "start"

  resources :agents

  resources :partners

  resources :appointments

  resources :steps_logs

  resources :lead_steps

  resources :lead_sources

  resources :installer_statuses

  resources :agent_statuses

  resources :partner_statuses

  resources :package_statuses

  resources :appointment_statuses

  resources :contact_statuses

  resources :lead_statuses

  resources :contact_types

  resources :user_types

  resources :agent_types

end

app/models/lead_source.rb
class LeadSource < ActiveRecord::Base
  attr_accessible :notes, :source
end

app/controllers/lead_sources_controller.rb
class LeadSourcesController < ApplicationController
  # GET /lead_sources
  # GET /lead_sources.json
  def index
    @lead_sources = LeadSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lead_sources }
    end
  end

  # GET /lead_sources/1
  # GET /lead_sources/1.json
  def show
    @lead_source = LeadSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead_source }
    end
  end

  # GET /lead_sources/new
  # GET /lead_sources/new.json
  def new
    @lead_source = LeadSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead_source }
    end
  end

  # GET /lead_sources/1/edit
  def edit
    @lead_source = LeadSource.find(params[:id])
  end

  # POST /lead_sources
  # POST /lead_sources.json
  def create
    @lead_source = LeadSource.new(params[:lead_source])

    respond_to do |format|
      if @lead_source.save
        format.html { redirect_to @lead_source, notice: 'Lead source was successfully created.' }
        format.json { render json: @lead_source, status: :created, location: @lead_source }
      else
        format.html { render action: "new" }
        format.json { render json: @lead_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lead_sources/1
  # PUT /lead_sources/1.json
  def update
    @lead_source = LeadSource.find(params[:id])

    respond_to do |format|
      if @lead_source.update_attributes(params[:lead_source])
        format.html { redirect_to @lead_source, notice: 'Lead source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lead_sources/1
  # DELETE /lead_sources/1.json
  def destroy
    @lead_source = LeadSource.find(params[:id])
    @lead_source.destroy

    respond_to do |format|
      format.html { redirect_to lead_sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lead_sources_helper.rb
module LeadSourcesHelper
end

app/views/lead_sources/_form.html.erb
<%= form_for(@lead_source) do |f| %>
  <% if @lead_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead_source.errors.count, "error") %> prohibited this lead_source from being saved:</h2>

      <ul>
      <% @lead_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lead_sources/edit.html.erb
<h1>Editing lead_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead_source %> |
<%= link_to 'Back', lead_sources_path %>

app/views/lead_sources/index.html.erb
<h1>Listing lead_sources</h1>

<table>
  <tr>
    <th>Source</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lead_sources.each do |lead_source| %>
  <tr>
    <td><%= lead_source.source %></td>
    <td><%= lead_source.notes %></td>
    <td><%= link_to 'Show', lead_source %></td>
    <td><%= link_to 'Edit', edit_lead_source_path(lead_source) %></td>
    <td><%= link_to 'Destroy', lead_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lead source', new_lead_source_path %>

app/views/lead_sources/new.html.erb
<h1>New lead_source</h1>

<%= render 'form' %>

<%= link_to 'Back', lead_sources_path %>

app/views/lead_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source:</b>
  <%= @lead_source.source %>
</p>

<p>
  <b>Notes:</b>
  <%= @lead_source.notes %>
</p>


<%= link_to 'Edit', edit_lead_source_path(@lead_source) %> |
<%= link_to 'Back', lead_sources_path %>