config/routes.rb
LeadTracker::Application.routes.draw do

  get "lead_notes/get_notes"
  resources :lead_notes

  get "schedule/add_appointment"

  get "schedule/get_appointments"

  resources :partner_types

  resource :session

  match '/login' => "sessions#new", :as => "login"

  match '/logout' => "sessions#destroy", :as => "logout"

  resources :packages

  resources :installers

  resources :users

  match 'leads/new_lead' => "leads#new_lead"
  match 'leads/my_lead_status' => "leads#my_lead_status"
  match 'leads/partner_lead_status' => "leads#partner_lead_status"
  match 'leads/lead_admin' => "leads#lead_admin"
  resources :leads

  match 'agents/start' => "agents#start"# , :as => "start"

  resources :agents

  resources :partners

  resources :appointments

  resources :steps_logs

  resources :lead_steps

  resources :lead_sources

  resources :installer_statuses

  resources :agent_statuses

  resources :partner_statuses

  resources :package_statuses

  resources :appointment_statuses

  resources :contact_statuses

  resources :lead_statuses

  resources :contact_types

  resources :user_types

  resources :agent_types

end

app/controllers/appointment_statuses_controller.rb
class AppointmentStatusesController < ApplicationController
  # GET /appointment_statuses
  # GET /appointment_statuses.json
  def index
    @appointment_statuses = AppointmentStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointment_statuses }
    end
  end

  # GET /appointment_statuses/1
  # GET /appointment_statuses/1.json
  def show
    @appointment_status = AppointmentStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment_status }
    end
  end

  # GET /appointment_statuses/new
  # GET /appointment_statuses/new.json
  def new
    @appointment_status = AppointmentStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment_status }
    end
  end

  # GET /appointment_statuses/1/edit
  def edit
    @appointment_status = AppointmentStatus.find(params[:id])
  end

  # POST /appointment_statuses
  # POST /appointment_statuses.json
  def create
    @appointment_status = AppointmentStatus.new(params[:appointment_status])

    respond_to do |format|
      if @appointment_status.save
        format.html { redirect_to @appointment_status, notice: 'Appointment status was successfully created.' }
        format.json { render json: @appointment_status, status: :created, location: @appointment_status }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointment_statuses/1
  # PUT /appointment_statuses/1.json
  def update
    @appointment_status = AppointmentStatus.find(params[:id])

    respond_to do |format|
      if @appointment_status.update_attributes(params[:appointment_status])
        format.html { redirect_to @appointment_status, notice: 'Appointment status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_statuses/1
  # DELETE /appointment_statuses/1.json
  def destroy
    @appointment_status = AppointmentStatus.find(params[:id])
    @appointment_status.destroy

    respond_to do |format|
      format.html { redirect_to appointment_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/appointment_statuses_helper.rb
module AppointmentStatusesHelper
end

app/views/appointment_statuses/_form.html.erb
<%= form_for(@appointment_status) do |f| %>
  <% if @appointment_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment_status.errors.count, "error") %> prohibited this appointment_status from being saved:</h2>

      <ul>
      <% @appointment_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointment_statuses/edit.html.erb
<h1>Editing appointment_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment_status %> |
<%= link_to 'Back', appointment_statuses_path %>

app/views/appointment_statuses/index.html.erb
<h1>Listing appointment_statuses</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointment_statuses.each do |appointment_status| %>
  <tr>
    <td><%= appointment_status.status %></td>
    <td><%= appointment_status.notes %></td>
    <td><%= link_to 'Show', appointment_status %></td>
    <td><%= link_to 'Edit', edit_appointment_status_path(appointment_status) %></td>
    <td><%= link_to 'Destroy', appointment_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Appointment status', new_appointment_status_path %>

app/views/appointment_statuses/new.html.erb
<h1>New appointment_status</h1>

<%= render 'form' %>

<%= link_to 'Back', appointment_statuses_path %>

app/views/appointment_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @appointment_status.status %>
</p>

<p>
  <b>Notes:</b>
  <%= @appointment_status.notes %>
</p>


<%= link_to 'Edit', edit_appointment_status_path(@appointment_status) %> |
<%= link_to 'Back', appointment_statuses_path %>