config/routes.rb
LeadTracker::Application.routes.draw do

  get "lead_notes/get_notes"
  resources :lead_notes

  get "schedule/add_appointment"

  get "schedule/get_appointments"

  resources :partner_types

  resource :session

  match '/login' => "sessions#new", :as => "login"

  match '/logout' => "sessions#destroy", :as => "logout"

  resources :packages

  resources :installers

  resources :users

  match 'leads/new_lead' => "leads#new_lead"
  match 'leads/my_lead_status' => "leads#my_lead_status"
  match 'leads/partner_lead_status' => "leads#partner_lead_status"
  match 'leads/lead_admin' => "leads#lead_admin"
  resources :leads

  match 'agents/start' => "agents#start"# , :as => "start"

  resources :agents

  resources :partners

  resources :appointments

  resources :steps_logs

  resources :lead_steps

  resources :lead_sources

  resources :installer_statuses

  resources :agent_statuses

  resources :partner_statuses

  resources :package_statuses

  resources :appointment_statuses

  resources :contact_statuses

  resources :lead_statuses

  resources :contact_types

  resources :user_types

  resources :agent_types

end

app/controllers/installer_statuses_controller.rb
class InstallerStatusesController < ApplicationController
  # GET /installer_statuses
  # GET /installer_statuses.json
  def index
    @installer_statuses = InstallerStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @installer_statuses }
    end
  end

  # GET /installer_statuses/1
  # GET /installer_statuses/1.json
  def show
    @installer_status = InstallerStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @installer_status }
    end
  end

  # GET /installer_statuses/new
  # GET /installer_statuses/new.json
  def new
    @installer_status = InstallerStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @installer_status }
    end
  end

  # GET /installer_statuses/1/edit
  def edit
    @installer_status = InstallerStatus.find(params[:id])
  end

  # POST /installer_statuses
  # POST /installer_statuses.json
  def create
    @installer_status = InstallerStatus.new(params[:installer_status])

    respond_to do |format|
      if @installer_status.save
        format.html { redirect_to @installer_status, notice: 'Installer status was successfully created.' }
        format.json { render json: @installer_status, status: :created, location: @installer_status }
      else
        format.html { render action: "new" }
        format.json { render json: @installer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /installer_statuses/1
  # PUT /installer_statuses/1.json
  def update
    @installer_status = InstallerStatus.find(params[:id])

    respond_to do |format|
      if @installer_status.update_attributes(params[:installer_status])
        format.html { redirect_to @installer_status, notice: 'Installer status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @installer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /installer_statuses/1
  # DELETE /installer_statuses/1.json
  def destroy
    @installer_status = InstallerStatus.find(params[:id])
    @installer_status.destroy

    respond_to do |format|
      format.html { redirect_to installer_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/installer_statuses_helper.rb
module InstallerStatusesHelper
end

app/views/installer_statuses/_form.html.erb
<%= form_for(@installer_status) do |f| %>
  <% if @installer_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@installer_status.errors.count, "error") %> prohibited this installer_status from being saved:</h2>

      <ul>
      <% @installer_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/installer_statuses/edit.html.erb
<h1>Editing installer_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @installer_status %> |
<%= link_to 'Back', installer_statuses_path %>

app/views/installer_statuses/index.html.erb
<h1>Listing installer_statuses</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @installer_statuses.each do |installer_status| %>
  <tr>
    <td><%= installer_status.status %></td>
    <td><%= installer_status.notes %></td>
    <td><%= link_to 'Show', installer_status %></td>
    <td><%= link_to 'Edit', edit_installer_status_path(installer_status) %></td>
    <td><%= link_to 'Destroy', installer_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Installer status', new_installer_status_path %>

app/views/installer_statuses/new.html.erb
<h1>New installer_status</h1>

<%= render 'form' %>

<%= link_to 'Back', installer_statuses_path %>

app/views/installer_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @installer_status.status %>
</p>

<p>
  <b>Notes:</b>
  <%= @installer_status.notes %>
</p>


<%= link_to 'Edit', edit_installer_status_path(@installer_status) %> |
<%= link_to 'Back', installer_statuses_path %>