config/routes.rb
LeadTracker::Application.routes.draw do

  get "lead_notes/get_notes"
  resources :lead_notes

  get "schedule/add_appointment"

  get "schedule/get_appointments"

  resources :partner_types

  resource :session

  match '/login' => "sessions#new", :as => "login"

  match '/logout' => "sessions#destroy", :as => "logout"

  resources :packages

  resources :installers

  resources :users

  match 'leads/new_lead' => "leads#new_lead"
  match 'leads/my_lead_status' => "leads#my_lead_status"
  match 'leads/partner_lead_status' => "leads#partner_lead_status"
  match 'leads/lead_admin' => "leads#lead_admin"
  resources :leads

  match 'agents/start' => "agents#start"# , :as => "start"

  resources :agents

  resources :partners

  resources :appointments

  resources :steps_logs

  resources :lead_steps

  resources :lead_sources

  resources :installer_statuses

  resources :agent_statuses

  resources :partner_statuses

  resources :package_statuses

  resources :appointment_statuses

  resources :contact_statuses

  resources :lead_statuses

  resources :contact_types

  resources :user_types

  resources :agent_types

end

app/controllers/lead_statuses_controller.rb
class LeadStatusesController < ApplicationController
  # GET /lead_statuses
  # GET /lead_statuses.json
  def index
    @lead_statuses = LeadStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lead_statuses }
    end
  end

  # GET /lead_statuses/1
  # GET /lead_statuses/1.json
  def show
    @lead_status = LeadStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead_status }
    end
  end

  # GET /lead_statuses/new
  # GET /lead_statuses/new.json
  def new
    @lead_status = LeadStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead_status }
    end
  end

  # GET /lead_statuses/1/edit
  def edit
    @lead_status = LeadStatus.find(params[:id])
  end

  # POST /lead_statuses
  # POST /lead_statuses.json
  def create
    @lead_status = LeadStatus.new(params[:lead_status])

    respond_to do |format|
      if @lead_status.save
        format.html { redirect_to @lead_status, notice: 'Lead status was successfully created.' }
        format.json { render json: @lead_status, status: :created, location: @lead_status }
      else
        format.html { render action: "new" }
        format.json { render json: @lead_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lead_statuses/1
  # PUT /lead_statuses/1.json
  def update
    @lead_status = LeadStatus.find(params[:id])

    respond_to do |format|
      if @lead_status.update_attributes(params[:lead_status])
        format.html { redirect_to @lead_status, notice: 'Lead status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lead_statuses/1
  # DELETE /lead_statuses/1.json
  def destroy
    @lead_status = LeadStatus.find(params[:id])
    @lead_status.destroy

    respond_to do |format|
      format.html { redirect_to lead_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lead_statuses_helper.rb
module LeadStatusesHelper
end

app/views/lead_statuses/_form.html.erb
<%= form_for(@lead_status) do |f| %>
  <% if @lead_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead_status.errors.count, "error") %> prohibited this lead_status from being saved:</h2>

      <ul>
      <% @lead_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lead_statuses/edit.html.erb
<h1>Editing lead_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead_status %> |
<%= link_to 'Back', lead_statuses_path %>

app/views/lead_statuses/index.html.erb
<h1>Listing lead_statuses</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lead_statuses.each do |lead_status| %>
  <tr>
    <td><%= lead_status.status %></td>
    <td><%= lead_status.notes %></td>
    <td><%= link_to 'Show', lead_status %></td>
    <td><%= link_to 'Edit', edit_lead_status_path(lead_status) %></td>
    <td><%= link_to 'Destroy', lead_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lead status', new_lead_status_path %>

app/views/lead_statuses/new.html.erb
<h1>New lead_status</h1>

<%= render 'form' %>

<%= link_to 'Back', lead_statuses_path %>

app/views/lead_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @lead_status.status %>
</p>

<p>
  <b>Notes:</b>
  <%= @lead_status.notes %>
</p>


<%= link_to 'Edit', edit_lead_status_path(@lead_status) %> |
<%= link_to 'Back', lead_statuses_path %>